navbar:
  blog_title: 醉里博客
  ground_glass:
    enable: true
index:
  banner_img: /images/uploads/bbc58c3d998d4f389fdae649334873f7.jpg
  banner_img_height: 100
  slogan:
    text: 醉里挑灯看剑，梦回吹角连营。
post:
  banner_img: /images/uploads/1616421416500-wallhaven-rddv31.jpg
  banner_img_height: 70
  default_index_img: /images/uploads/default_post_img.png
archive:
  banner_img: /images/uploads/1616421416500-wallhaven-rddv31.jpg
  banner_img_height: 80
  subtitle: null
category:
  banner_img: /images/uploads/1616421416500-wallhaven-rddv31.jpg
  banner_img_height: 80
  subtitle: null
tag:
  banner_img: /images/uploads/1616421669417-wallhaven-1kkm2g.jpg
  banner_img_height: 80
  subtitle: null
about:
  banner_img: /images/uploads/wallhaven-pkkr2.webp
  banner_img_height: 80
  subtitle: null
  avatar: /images/uploads/yutzi.jpg
  name: 醉里
  intro: My blog
links:
  banner_img: /images/uploads/1616421416500-wallhaven-rddv31.jpg
  banner_img_height: 80
  subtitle: null
  items:
    - title: 小理の小窝
      intro: 一个普通学生的普通生活
      link: https://xiaolii.com/
      avatar: https://502.chat/Imagesource/icon.jpg
    - title: Diary of LX
      intro: 随便写写
      link: https://diary.bid/
      avatar: https://diary.bid/wp-content/uploads/2022/11/%E4%B8%8B%E8%BD%BD.jpg
    - title: 安知鱼
      link: "https://anzhiy.cn/ "
      intro: 生活明朗，万物可爱
      avatar: https://image.anzhiy.cn/adminuploads/1/2022/09/15/63232b7d91d22.jpg
    - title: 张洪Heo
      link: https://blog.zhheo.com/
      intro: 分享设计与科技生活
      avatar: https://img.zhheo.com/i/2022/08/19/62ff32fa28da1.png
    - title: 青衣
      link: https://www.qingyi1220.cn/
      intro: 世界既不黑也不白，而是一道精致的灰
      avatar: https://www.qingyi1220.cn/img/Tsingyi.jpg
