navbar:
  blog_title: 醉里博客
  ground_glass:
    enable: true
index:
  banner_img: https://pic.imgdb.cn/item/6393f03ab1fccdcd3610d927.jpg
  banner_img_height: 100
  slogan:
    text: 醉里挑灯看剑，梦回吹角连营。
post:
  banner_img: /images/uploads/1616421416500-wallhaven-rddv31.jpg
  banner_img_height: 70
  default_index_img: /images/uploads/default_post_img.png
archive:
  banner_img: /images/uploads/1616421416500-wallhaven-rddv31.jpg
  banner_img_height: 80
  subtitle: null
category:
  banner_img: /images/uploads/1616421416500-wallhaven-rddv31.jpg
  banner_img_height: 80
  subtitle: null
tag:
  banner_img: /images/uploads/1616421669417-wallhaven-1kkm2g.jpg
  banner_img_height: 80
  subtitle: null
about:
  banner_img: /images/uploads/wallhaven-pkkr2.webp
  banner_img_height: 80
  subtitle: null
  avatar: /images/uploads/yutzi.jpg
  name: 醉里
  intro: My blog
links:
  banner_img: /images/uploads/1616421416500-wallhaven-rddv31.jpg
  banner_img_height: 80
  subtitle: null
  items:
    - title: 小理の小窝
      intro: 一个普通学生的普通生活
      link: https://xiaolii.com/
      avatar: https://502.chat/Imagesource/icon.jpg
    - title: Diary of LX
      intro: 随便写写
      link: https://diary.bid/
      avatar: https://diary.bid/wp-content/uploads/2022/11/%E4%B8%8B%E8%BD%BD.jpg
    - title: 安知鱼
      link: "https://anzhiy.cn/ "
      intro: 生活明朗，万物可爱
      avatar: https://image.anzhiy.cn/adminuploads/1/2022/09/15/63232b7d91d22.jpg
    - title: 张洪Heo
      link: https://blog.zhheo.com/
      intro: 分享设计与科技生活
      avatar: https://img.zhheo.com/i/2022/08/19/62ff32fa28da1.png
    - title: 青衣
      link: https://www.qingyi1220.cn/
      intro: 世界既不黑也不白，而是一道精致的灰
      avatar: https://www.qingyi1220.cn/img/Tsingyi.jpg
    - title: XKの博客
      link: https://www.xukaiyyds.cn/
      avatar: https://www.xukaiyyds.cn/img/favicon.png
      intro: 一个干净整洁的个人博客
    - avatar: https://cdn.dusays.com/avatar.png
      link: https://dusays.com/
      title: 杜老师说
    - title: 8：9社区
      intro: 用一生去抵达遥远的未来
      avatar: https://cdn.sady0.com/pic/%E8%B5%84%E6%BA%90%2050000.png
      link: https://8b9.cn
    - title: 小染笔记
      intro: 遇见即是上上签.
      link: https://sady0.com/
      avatar: https://cdn.sady0.com/pic/91531896_p0.jpg
    - title: Mycpen
      link: https://cpen.top/
      avatar: https://image.cpen.top/image/avatar.jpg
      intro: 这是一个有趣的博客
    - title: Xlenco
      link: https://xlenco.eu.org/
      intro: 最好的地方,是没去过的地方。最好的时光，是回不来的时光。
      avatar: https://xlenco.eu.org/img/head.webp
    - title: 兔芽网
      intro: 优麦兔旗下新松计划产品
      link: https://www.tuya.ink/
      avatar: https://www.tuya.ink/wp-content/uploads/2022/12/72d5fbcf44170825.png
